Repository RGPosadas/Mull, pull requests merged in 2020-11, with the labels that each got.

#59 US-1.1: Create Events
  README.md
  apps/mull-api/src/app/app.module.ts
  apps/mull-api/src/app/entities/event.entity.ts
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/app/event/event.mockdata.ts
  apps/mull-api/src/app/event/event.module.ts
  apps/mull-api/src/app/event/event.resolver.spec.ts
  apps/mull-api/src/app/event/event.resolver.ts
  apps/mull-api/src/app/event/event.service.spec.ts
  apps/mull-api/src/app/event/event.service.ts
  apps/mull-api/src/app/event/inputs/event.input.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui-e2e/src/integration/create-event.spec.ts
  apps/mull-ui/src/app/__snapshots__/app.spec.tsx.snap
  apps/mull-ui/src/app/app.scss
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/navigation-bar/navigation-bar.scss
  apps/mull-ui/src/app/pages/create-event/create-event.scss
  apps/mull-ui/src/app/pages/create-event/create-event.spec.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/create-event/date-calendar/date-calendar.scss
  apps/mull-ui/src/app/pages/create-event/date-calendar/date-calendar.spec.tsx
  apps/mull-ui/src/app/pages/create-event/date-calendar/date-calendar.tsx
  apps/mull-ui/src/assets/icons/event-form-icons/description.svg
  apps/mull-ui/src/assets/icons/event-form-icons/pencil.svg
  apps/mull-ui/src/assets/icons/event-form-icons/pin.svg
  apps/mull-ui/src/assets/icons/event-form-icons/upload.svg
  apps/mull-ui/src/constants.ts
  apps/mull-ui/src/environments/environment.ts
  apps/mull-ui/src/main.tsx
  libs/types/src/lib/types.ts
  libs/ui-lib/src/index.ts
  libs/ui-lib/src/lib/custom-text-input/__snapshots__/custom-text-input.spec.tsx.snap
  libs/ui-lib/src/lib/custom-text-input/custom-text-input.scss
  libs/ui-lib/src/lib/custom-text-input/custom-text-input.spec.tsx
  libs/ui-lib/src/lib/custom-text-input/custom-text-input.tsx
  libs/ui-lib/src/lib/custom-time-picker/__snapshots__/custom-time-picker.spec.tsx.snap
  libs/ui-lib/src/lib/custom-time-picker/custom-time-picker.scss
  libs/ui-lib/src/lib/custom-time-picker/custom-time-picker.spec.tsx
  libs/ui-lib/src/lib/custom-time-picker/custom-time-picker.tsx
  libs/ui-lib/src/lib/pill-options/__snapshots__/pill-options.spec.tsx.snap
  libs/ui-lib/src/lib/pill-options/pill-options.scss
  libs/ui-lib/src/lib/pill-options/pill-options.spec.tsx
  libs/ui-lib/src/lib/pill-options/pill-options.tsx
  libs/ui-lib/src/lib/styles/styles.scss
  libs/ui-lib/src/lib/styles/variables.scss
  package-lock.json
  package.json
  scripts/check-affected.sh
  scripts/check-all.sh
  scripts/ci-checks.sh
  workspace.json
Labels: adds npm packages

#61 REFACTOR/TEST: let e2e tests run in both mobile and desktop view
  apps/mull-ui-e2e/src/integration/create-event.spec.ts
  apps/mull-ui/src/app/components/navigation-bar/navigation-bar.scss
Labels: refactor

#83 FIX: Add font awesome and remove some svgs
  apps/mull-ui/src/app/logo.svg
  apps/mull-ui/src/app/pages/create-event/create-event.scss
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/star.svg
  apps/mull-ui/src/assets/icons/event-form-icons/description.svg
  apps/mull-ui/src/assets/icons/event-form-icons/pencil.svg
  apps/mull-ui/src/assets/icons/event-form-icons/pin.svg
  apps/mull-ui/src/assets/icons/event-form-icons/upload.svg
  libs/ui-lib/src/lib/custom-text-input/custom-text-input.scss
  package-lock.json
  package.json
Labels: adds npm packages, refactor

#82 TASK-22: Back button
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/header/header.spec.tsx
  apps/mull-ui/src/app/components/index.ts
  apps/mull-ui/src/app/components/mull-back-button/__snapshots__/mull-back-button.spec.tsx.snap
  apps/mull-ui/src/app/components/mull-back-button/mull-back-button.scss
  apps/mull-ui/src/app/components/mull-back-button/mull-back-button.spec.tsx
  apps/mull-ui/src/app/components/mull-back-button/mull-back-button.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  libs/ui-lib/src/lib/custom-text-input/custom-text-input.spec.tsx
  libs/ui-lib/src/lib/custom-time-picker/custom-time-picker.spec.tsx
  libs/ui-lib/src/lib/styles/styles.scss
Labels: refactor

#80 TASK-17: Event Page
  .eslintrc
  apps/mull-api/src/app/entities/event.entity.ts
  apps/mull-api/src/app/entities/location.entity.ts
  apps/mull-api/src/app/entities/media.entity.ts
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui/src/app/app.scss
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/event-page-header/__snapshots__/event-page-header.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-header/event-page-header.scss
  apps/mull-ui/src/app/components/event-page-header/event-page-header.spec.tsx
  apps/mull-ui/src/app/components/event-page-header/event-page-header.tsx
  apps/mull-ui/src/app/components/event-page-info/__snapshots__/event-page-info.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-info/event-page-info.scss
  apps/mull-ui/src/app/components/event-page-info/event-page-info.spec.tsx
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/components/expandable-text/__snapshots__/expandable-text.spec.tsx.snap
  apps/mull-ui/src/app/components/expandable-text/expandable-text.scss
  apps/mull-ui/src/app/components/expandable-text/expandable-text.spec.tsx
  apps/mull-ui/src/app/components/expandable-text/expandable-text.tsx
  apps/mull-ui/src/app/components/index.ts
  apps/mull-ui/src/app/components/mull-back-button/__snapshots__/mull-back-button.spec.tsx.snap
  apps/mull-ui/src/app/components/mull-back-button/mull-back-button.spec.tsx
  apps/mull-ui/src/app/components/mull-back-button/mull-back-button.tsx
  apps/mull-ui/src/app/components/mull-button/__snapshots__/mull-button.spec.tsx.snap
  apps/mull-ui/src/app/components/mull-button/mull-button.scss
  apps/mull-ui/src/app/components/mull-button/mull-button.spec.tsx
  apps/mull-ui/src/app/components/mull-button/mull-button.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.scss
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/event-page/__snapshots__/event-page.spec.tsx.snap
  apps/mull-ui/src/app/pages/event-page/event-page.scss
  apps/mull-ui/src/app/pages/event-page/event-page.spec.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
  apps/mull-ui/src/constants.ts
  libs/types/src/lib/types.ts
  libs/ui-lib/src/lib/styles/styles.scss
  package-lock.json
  package.json
Labels: adds npm packages

#77 US-1.2: upload event page photo
  .eslintrc
  .pre-commit-config.yaml
  apps/mull-api/src/app/entities/event.entity.ts
  apps/mull-api/src/app/entities/media.entity.ts
  apps/mull-api/src/app/event/inputs/event.input.ts
  apps/mull-api/src/app/media/inputs/media.input.ts
  apps/mull-api/src/app/media/media.mockdata.ts
  apps/mull-api/src/app/media/media.resolver.spec.ts
  apps/mull-api/src/app/media/media.resolver.ts
  apps/mull-api/src/app/media/media.service.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui-e2e/src/fixtures/zoro.jpg
  apps/mull-ui-e2e/src/integration/US-1.1.spec.ts
  apps/mull-ui/src/app/components/custom-file-upload/custom-file-upload.scss
  apps/mull-ui/src/app/components/custom-file-upload/custom-file-upload.spec.tsx
  apps/mull-ui/src/app/components/custom-file-upload/custom-file-upload.tsx
  apps/mull-ui/src/app/components/index.ts
  apps/mull-ui/src/app/pages/create-event/create-event.scss
  apps/mull-ui/src/app/pages/create-event/create-event.spec.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/create-event/date-calendar/date-calendar.scss
  apps/mull-ui/src/main.tsx
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
Labels: adds npm packages, refactor

#90 TASK-19: Multiple Registration Options Back-end
  apps/mull-api/src/app/app.module.ts
  apps/mull-api/src/app/auth/auth.controller.spec.ts
  apps/mull-api/src/app/auth/auth.controller.ts
  apps/mull-api/src/app/auth/auth.module.ts
  apps/mull-api/src/app/auth/auth.service.spec.ts
  apps/mull-api/src/app/auth/auth.service.ts
  apps/mull-api/src/app/auth/facebook.strategy.ts
  apps/mull-api/src/app/auth/google.strategy.ts
  apps/mull-api/src/app/auth/local.strategy.ts
  apps/mull-api/src/app/auth/twitter.strategy.ts
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/app/user/inputs/user.input.ts
  apps/mull-api/src/app/user/user.mockdata.ts
  apps/mull-api/src/app/user/user.module.ts
  apps/mull-api/src/app/user/user.service.ts
  apps/mull-api/src/environments/environment.ts
  apps/mull-api/src/main.ts
  apps/mull-api/src/schema.gql
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
Labels: adds npm packages, backend

#96 US-1.8: Review Event Creation
  apps/mull-api/uploads/.gitignore
  apps/mull-ui-e2e/src/fixtures/frame-sizes.ts
  apps/mull-ui-e2e/src/integration/US-1.1.spec.ts
  apps/mull-ui-e2e/src/integration/US-1.8.spec.ts
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/event-page-header/__snapshots__/event-page-header.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-header/event-page-header.spec.tsx
  apps/mull-ui/src/app/components/event-page-header/event-page-header.tsx
  apps/mull-ui/src/app/components/event-page-info/__snapshots__/event-page-info.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/components/mull-button/__snapshots__/mull-button.spec.tsx.snap
  apps/mull-ui/src/app/components/mull-button/mull-button.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/event-page/__snapshots__/event-page.spec.tsx.snap
  apps/mull-ui/src/app/pages/event-page/event-page.spec.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
Labels: refactor

#103 SONARCLOUD: Fix Code Smells
  apps/mull-api/src/app/media/media.mockdata.ts
  apps/mull-ui/src/app/pages/create-event/create-event.scss
  apps/mull-ui/src/app/pages/login/login.scss
  libs/ui-lib/src/lib/ui-lib.scss
  libs/ui-lib/src/lib/ui-lib.tsx
Labels: refactor
