Repository RGPosadas/Mull, pull requests merged in 2020-12, with the labels that each got.

#108 BUG-7: SwipeableRoutes Not working
  apps/mull-ui/src/app/app.tsx
Labels: bug, frontend

#110 US-7.1: Multiple Registration Options
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/app/user/inputs/user.input.ts
  apps/mull-api/src/app/user/user.mockdata.ts
  apps/mull-api/src/app/user/user.resolver.spec.ts
  apps/mull-api/src/app/user/user.resolver.ts
  apps/mull-api/src/app/user/user.service.spec.ts
  apps/mull-api/src/app/user/user.service.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui-e2e/src/integration/US-7.1.spec.ts
  apps/mull-ui/src/app/hooks/useToast.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/login/login.scss
  apps/mull-ui/src/app/pages/login/login.spec.tsx
  apps/mull-ui/src/app/pages/login/login.tsx
  apps/mull-ui/src/app/pages/register/register.spec.tsx
  apps/mull-ui/src/app/pages/register/register.tsx
  apps/mull-ui/src/environments/environment.ts
  apps/mull-ui/src/main.tsx
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
Labels: refactor

#116 TASK-32: Joining an Event backend
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/app/event/event.mockdata.ts
  apps/mull-api/src/app/event/event.resolver.spec.ts
  apps/mull-api/src/app/event/event.resolver.ts
  apps/mull-api/src/app/event/event.service.spec.ts
  apps/mull-api/src/app/event/event.service.ts
  apps/mull-api/src/schema.gql
Labels: refactor

#123 TASK-29: Login Backend
  apps/mull-api/src/app/app.module.ts
  apps/mull-api/src/app/auth/auth.controller.spec.ts
  apps/mull-api/src/app/auth/auth.controller.ts
  apps/mull-api/src/app/auth/auth.module.ts
  apps/mull-api/src/app/auth/auth.resolver.spec.ts
  apps/mull-api/src/app/auth/auth.resolver.ts
  apps/mull-api/src/app/auth/auth.service.spec.ts
  apps/mull-api/src/app/auth/auth.service.ts
  apps/mull-api/src/app/auth/inputs/auth.input.ts
  apps/mull-api/src/app/auth/local.strategy.ts
  apps/mull-api/src/app/auth/strategies/facebook.strategy.ts
  apps/mull-api/src/app/auth/strategies/google.strategy.ts
  apps/mull-api/src/app/auth/strategies/twitter.strategy.ts
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/app/user/user.mockdata.ts
  apps/mull-api/src/app/user/user.service.spec.ts
  apps/mull-api/src/app/user/user.service.ts
  apps/mull-api/src/environments/environment.ts
  apps/mull-api/src/main.ts
  apps/mull-api/src/schema.gql
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
Labels: adds npm packages, backend
