Repository RGPosadas/Mull, pull requests merged in 2021-02, with the labels that each got.

#202 TASK-55: Process tfjs model output
  README.md
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/navigation/bot-nav-bar/__snapshots__/bot-nav-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation/nav-buttons/nav-buttons.tsx
  apps/mull-ui/src/app/components/navigation/top-nav-bar/__snapshots__/top-nav-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation/top-nav-bar/top-nav-bar.spec.tsx
  apps/mull-ui/src/app/pages/trash-recognition-page/trash-recognition-page.scss
  apps/mull-ui/src/app/pages/trash-recognition-page/trash-recognition-page.spec.tsx
  apps/mull-ui/src/app/pages/trash-recognition-page/trash-recognition-page.tsx
  apps/mull-ui/src/app/services/maps.ts
  apps/mull-ui/src/app/services/tfjs.model.spec.ts
  apps/mull-ui/src/app/services/tfjs.model.ts
  apps/mull-ui/src/constants.ts
  libs/types/src/lib/types.ts
  ml/trash-recognition/annotations/label_map.pbtxt
  ml/trash-recognition/generate_tfrecord.py
  ml/trash-recognition/models/mull-model/pipeline.config
  ml/trash-recognition/test-model.ipynb
  package-lock.json
  package.json
Labels: adds npm packages, frontend

#200 TASK-45: Authenticated Backend Routes
  .gitignore
  README.md
  apps/mull-api/src/app/auth/auth.guard.spec.ts
  apps/mull-api/src/app/auth/auth.guard.ts
  apps/mull-api/src/app/event/event.resolver.spec.ts
  apps/mull-api/src/app/event/event.resolver.ts
  apps/mull-api/src/app/event/event.service.spec.ts
  apps/mull-api/src/app/event/event.service.ts
  apps/mull-api/src/app/event/inputs/event.input.ts
  apps/mull-api/src/app/location/location.resolver.ts
  apps/mull-api/src/app/media/media.resolver.ts
  apps/mull-api/src/app/user/user.resolver.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui-e2e/src/support/commands.ts
  apps/mull-ui/src/app/components/event-card/event-card.tsx
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.spec.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.spec.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.spec.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.spec.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.tsx
  apps/mull-ui/src/app/pages/profile/edit-profile/edit-profile.tsx
  apps/mull-ui/src/generated/graphql.tsx
  apps/mull-ui/src/graphql/mutations.gql
  apps/mull-ui/src/graphql/queries.gql
  package-lock.json
  package.json
Labels: adds npm packages, modifies env files

#214 TASK-46: Refresh Access Token after expiration
  apps/mull-ui/src/apollo/apollo-client.ts
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/main.tsx
  package-lock.json
  package.json
Labels: adds npm packages, frontend

#219 TASK-60: Authentication for Subscription
  apps/mull-api/src/app/app.module.ts
  apps/mull-api/src/app/auth/auth.guard.spec.ts
  apps/mull-api/src/app/auth/auth.guard.ts
  apps/mull-ui/src/apollo/apollo-client.ts
  apps/mull-ui/src/app/pages/messages/messages-page.spec.tsx
  apps/mull-ui/src/app/pages/messages/messages-page.tsx
  apps/mull-ui/src/environments/environment.prod.ts
  apps/mull-ui/src/environments/environment.ts
  apps/mull-ui/src/generated/graphql.tsx
  apps/mull-ui/src/graphql/subscriptions.gql
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
Labels: adds npm packages

#237 TASK-61: Emoji Support
  README.md
  apps/mull-api/src/app/app.module.ts
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/profile/edit-profile/edit-profile.tsx
  apps/mull-ui/src/app/pages/register/register.tsx
  apps/mull-ui/src/utilities.ts
  package-lock.json
  package.json
Labels: adds npm packages
