Repository RGPosadas/Mull, pull requests merged in 2021-03, with the labels that each got.

#250 TASK-71: DM's Backend
  apps/mull-api/src/app/channel/channel.mockdata.ts
  apps/mull-api/src/app/channel/channel.resolver.spec.ts
  apps/mull-api/src/app/channel/channel.resolver.ts
  apps/mull-api/src/app/channel/channel.service.spec.ts
  apps/mull-api/src/app/channel/channel.service.ts
  apps/mull-api/src/app/channel/inputs/channel.input.ts
  apps/mull-api/src/app/entities/channel.entity.ts
  apps/mull-api/src/app/entities/entities.module.ts
  apps/mull-api/src/app/entities/event.entity.ts
  apps/mull-api/src/app/entities/post.entity.ts
  apps/mull-api/src/app/entities/user.entity.ts
  apps/mull-api/src/app/event/event.service.ts
  apps/mull-api/src/app/post/post.mockdata.ts
  apps/mull-api/src/app/post/post.resolver.spec.ts
  apps/mull-api/src/app/post/post.service.spec.ts
  apps/mull-api/src/app/post/post.service.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui/src/app/pages/messages/event-chat/event-chat.spec.tsx
  apps/mull-ui/src/app/pages/messages/event-chat/event-chat.tsx
  apps/mull-ui/src/generated/graphql.tsx
  apps/mull-ui/src/graphql/queries.gql
Labels: backend

#258 TASK-66: Click Waste Recognition Page
  apps/mull-ui/src/app/pages/waste-recognition-page/identified-waste-modal.tsx
  apps/mull-ui/src/app/pages/waste-recognition-page/waste-recognition-page.tsx
  apps/mull-ui/src/constants.ts
  apps/mull-ui/src/utilities.spec.ts
  apps/mull-ui/src/utilities.ts
  libs/types/src/index.ts
  libs/types/src/ml.ts
  libs/types/src/types.ts
Labels: frontend

#260 TASK-62: Apply Usability Testing Feedback
  apps/mull-ui/src/app/components/event-card/__snapshots__/event-card.spec.tsx.snap
  apps/mull-ui/src/app/components/event-card/event-card.scss
  apps/mull-ui/src/app/components/event-card/event-card.tsx
  apps/mull-ui/src/app/components/navigation/top-nav-bar/__snapshots__/top-nav-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation/top-nav-bar/top-nav-bar.scss
  apps/mull-ui/src/app/components/navigation/top-nav-bar/top-nav-bar.tsx
  apps/mull-ui/src/app/components/profile-header/__snapshots__/profile-header.spec.tsx.snap
  apps/mull-ui/src/app/components/profile-header/profile-header.scss
  apps/mull-ui/src/app/components/profile-header/profile-header.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.scss
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/create-event/date-calendar/date-calendar.tsx
  apps/mull-ui/src/app/pages/event-page/event-page-info/event-page-info.scss
  apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.tsx
  apps/mull-ui/src/app/pages/profile/user-profile/__snapshots__/user-profile.spec.tsx.snap
  apps/mull-ui/src/assets/icons/join-icon.svg
  apps/mull-ui/src/utilities.ts
  package-lock.json
  package.json
Labels: adds npm packages

#298 TASK-72: Time Picker Slider
  apps/mull-ui-e2e/src/integration/US-1.1.spec.ts
  apps/mull-ui-e2e/src/integration/US-1.6.spec.ts
  apps/mull-ui-e2e/src/integration/US-1.8.spec.ts
  apps/mull-ui-e2e/src/integration/US-2.7.spec.ts
  apps/mull-ui/src/app/components/index.ts
  apps/mull-ui/src/app/components/time-slider/__snapshots__/time-slider.spec.tsx.snap
  apps/mull-ui/src/app/components/time-slider/time-slider.module.scss
  apps/mull-ui/src/app/components/time-slider/time-slider.scss
  apps/mull-ui/src/app/components/time-slider/time-slider.spec.tsx
  apps/mull-ui/src/app/components/time-slider/time-slider.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.spec.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/utilities.ts
  libs/types/src/forms.ts
  package-lock.json
  package.json
Labels: adds npm packages
