Repository RGPosadas/Mull, pull requests merged in 2021-01, with the labels that each got.

#135 HOTFIX: Fix failing e2e
  apps/mull-ui-e2e/src/integration/US-1.8.spec.ts
Labels: bug

#131 BUG-6: Event Picture is Uploaded before Review
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.spec.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
Labels: bug, frontend

#125 Refactor Navigation
  apps/mull-ui-e2e/src/integration/US-1.8.spec.ts
  apps/mull-ui/src/app/app.scss
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/event-card/__snapshots__/event-card.spec.tsx.snap
  apps/mull-ui/src/app/components/event-card/event-card.scss
  apps/mull-ui/src/app/components/event-card/event-card.spec.tsx
  apps/mull-ui/src/app/components/event-card/event-card.tsx
  apps/mull-ui/src/app/components/event-page-header/__snapshots__/event-page-header.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-header/event-page-header.spec.tsx
  apps/mull-ui/src/app/components/event-page-header/event-page-header.tsx
  apps/mull-ui/src/app/components/header/__snapshots__/header.spec.tsx.snap
  apps/mull-ui/src/app/components/header/header.scss
  apps/mull-ui/src/app/components/header/header.tsx
  apps/mull-ui/src/app/components/index.ts
  apps/mull-ui/src/app/components/navigation-bar/__snapshots__/navigation-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation-bar/navigation-bar.scss
  apps/mull-ui/src/app/components/navigation-bar/navigation-bar.tsx
  apps/mull-ui/src/app/components/navigation/bot-nav-bar/__snapshots__/bot-nav-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation/bot-nav-bar/bot-nav-bar.scss
  apps/mull-ui/src/app/components/navigation/bot-nav-bar/bot-nav-bar.spec.tsx
  apps/mull-ui/src/app/components/navigation/bot-nav-bar/bot-nav-bar.tsx
  apps/mull-ui/src/app/components/navigation/nav-buttons/nav-buttons.scss
  apps/mull-ui/src/app/components/navigation/nav-buttons/nav-buttons.spec.tsx
  apps/mull-ui/src/app/components/navigation/nav-buttons/nav-buttons.tsx
  apps/mull-ui/src/app/components/navigation/sub-nav-bar/__snapshots__/sub-nav-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar.scss
  apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar.spec.tsx
  apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar.tsx
  apps/mull-ui/src/app/components/navigation/top-nav-bar/__snapshots__/top-nav-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/navigation/top-nav-bar/top-nav-bar.scss
  apps/mull-ui/src/app/components/navigation/top-nav-bar/top-nav-bar.spec.tsx
  apps/mull-ui/src/app/components/navigation/top-nav-bar/top-nav-bar.tsx
  apps/mull-ui/src/app/components/subnavigation-bar/__snapshots__/subnavigation-bar.spec.tsx.snap
  apps/mull-ui/src/app/components/subnavigation-bar/subnavigation-bar.scss
  apps/mull-ui/src/app/components/subnavigation-bar/subnavigation-bar.tsx
  apps/mull-ui/src/app/pages/discover/discover.scss
  apps/mull-ui/src/app/pages/event-page/__snapshots__/event-page.spec.tsx.snap
  apps/mull-ui/src/app/pages/event-page/event-page.scss
  apps/mull-ui/src/styles.scss
  apps/mull-ui/src/variables.scss
Labels: refactor

#129 Us 2.1: Show Events as List Discover pages
  apps/mull-ui-e2e/src/integration/US-2.1.spec.ts
  apps/mull-ui/src/app/app.spec.tsx
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/components/event-card/__snapshots__/event-card.spec.tsx.snap
  apps/mull-ui/src/app/components/event-card/event-card.spec.tsx
  apps/mull-ui/src/app/components/event-card/event-card.tsx
  apps/mull-ui/src/app/components/event-page-header/__snapshots__/event-page-header.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-header/event-page-header.spec.tsx
  apps/mull-ui/src/app/components/event-page-header/event-page-header.tsx
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/discover/discover.scss
  apps/mull-ui/src/app/pages/discover/discover.spec.tsx
  apps/mull-ui/src/app/pages/discover/discover.tsx
  apps/mull-ui/src/app/pages/event-page/__snapshots__/event-page.spec.tsx.snap
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.spec.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
  apps/mull-ui/src/app/pages/home/home-discover.scss
  apps/mull-ui/src/app/pages/home/my-events/my-events.spec.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.spec.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.tsx
  apps/mull-ui/src/constants.ts
  apps/mull-ui/src/utilities.ts
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
Labels: adds npm packages

#138 TASK-31: Local Login Frontend Logic
  apps/mull-ui/src/app/app.tsx
  apps/mull-ui/src/app/context/user.context.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
  apps/mull-ui/src/app/pages/login/login.spec.tsx
  apps/mull-ui/src/app/pages/login/login.tsx
  apps/mull-ui/src/app/pages/register/register.spec.tsx
  apps/mull-ui/src/app/pages/register/register.tsx
  apps/mull-ui/src/constants.ts
  libs/types/src/index.ts
  libs/types/src/lib/forms.ts
  package-lock.json
  package.json
Labels: adds npm packages

#141 TASK-34: Setup GraphQL Codegen
  .pre-commit-config.yaml
  .prettierignore
  README.md
  apps/mull-ui/src/app/pages/create-event/create-event.spec.tsx
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.spec.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.spec.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.spec.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.tsx
  apps/mull-ui/src/app/pages/register/register.spec.tsx
  apps/mull-ui/src/app/pages/register/register.tsx
  apps/mull-ui/src/generated/graphql.tsx
  apps/mull-ui/src/graphql/mutations.gql
  apps/mull-ui/src/graphql/queries.gql
  codegen.yml
  package-lock.json
  package.json
Labels: adds npm packages

#121 TASK-28: Set Event Location
  apps/mull-api/axiosConfig.ts
  apps/mull-api/src/app/entities/location.entity.ts
  apps/mull-api/src/app/event/event.module.ts
  apps/mull-api/src/app/event/location-autocomplete/location-autocomplete.module.ts
  apps/mull-api/src/app/event/location-autocomplete/location-autocomplete.resolver.spec.ts
  apps/mull-api/src/app/event/location-autocomplete/location-autocomplete.resolver.ts
  apps/mull-api/src/environments/environment.prod.ts
  apps/mull-api/src/environments/environment.ts
  apps/mull-api/src/main.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui-e2e/src/fixtures/index.ts
  apps/mull-ui-e2e/src/fixtures/stubs.ts
  apps/mull-ui-e2e/src/integration/US-1.1.spec.ts
  apps/mull-ui-e2e/src/integration/US-1.8.spec.ts
  apps/mull-ui/src/app/components/custom-text-input/custom-text-input.tsx
  apps/mull-ui/src/app/components/event-page-info/__snapshots__/event-page-info.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/components/mull-back-button/mull-back-button.scss
  apps/mull-ui/src/app/pages/create-event/create-event.tsx
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/__snapshots__/location-autocomplete-modal.spec.tsx.snap
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/__snapshots__/location-autocomplete-textbox.spec.tsx.snap
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-modal.spec.tsx
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-modal.tsx
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-textbox.scss
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-textbox.spec.tsx
  apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-textbox.tsx
  apps/mull-ui/src/app/pages/event-page/__snapshots__/event-page.spec.tsx.snap
  apps/mull-ui/src/constants.ts
  apps/mull-ui/src/generated/graphql.tsx
  apps/mull-ui/src/graphql/queries.gql
  libs/types/src/lib/types.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: adds npm packages

#154 US-2.8: Joining events
  apps/mull-api/src/app/event/event.resolver.ts
  apps/mull-api/src/app/event/event.service.spec.ts
  apps/mull-api/src/app/event/event.service.ts
  apps/mull-api/src/schema.gql
  apps/mull-ui-e2e/src/integration/US-2.8.spec.ts
  apps/mull-ui/src/app/components/event-card/__snapshots__/event-card.spec.tsx.snap
  apps/mull-ui/src/app/components/event-card/event-card.spec.tsx
  apps/mull-ui/src/app/components/event-card/event-card.tsx
  apps/mull-ui/src/app/components/event-page-info/__snapshots__/event-page-info.spec.tsx.snap
  apps/mull-ui/src/app/components/event-page-info/event-page-info.scss
  apps/mull-ui/src/app/components/event-page-info/event-page-info.spec.tsx
  apps/mull-ui/src/app/components/event-page-info/event-page-info.tsx
  apps/mull-ui/src/app/pages/event-page/__snapshots__/event-page.spec.tsx.snap
  apps/mull-ui/src/app/pages/event-page/event-page.tsx
  apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
  apps/mull-ui/src/app/pages/home/my-events/my-events.tsx
  apps/mull-ui/src/app/pages/home/upcoming/upcoming.tsx
  apps/mull-ui/src/constants.ts
  apps/mull-ui/src/generated/graphql.tsx
  apps/mull-ui/src/graphql/mutations.gql
  apps/mull-ui/src/graphql/queries.gql
  apps/mull-ui/src/main.tsx
  libs/types/src/lib/types.ts
Labels: adds npm packages

#155 TASK-26: setup database seeding
  README.md
  apps/mull-api/src/app/entities/event.entity.ts
  apps/mull-api/src/database/factories/event.factory.ts
  apps/mull-api/src/database/factories/media.factory.ts
  apps/mull-api/src/database/factories/user.factory.ts
  apps/mull-api/src/database/seeders/database.seeder.ts
  apps/mull-api/src/environments/environment.prod.ts
  apps/mull-api/src/environments/environment.ts
  package-lock.json
  package.json
Labels: adds npm packages, modifies env files
